version: 2.1
jobs:
  build:
    docker:
      - image: <<parameters.docker_image>>
      - image: circleci/mysql:5.6
        command: mysqld --character-set-server=latin1 --collation-server=latin1_swedish_ci
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
    parameters:
        test_command:
            type: string
        docker_image:
            type: string
    environment:
      MOZ_HEADLESS: 1
      WORKBENCH_DATABASES: '{"default": {"ENGINE": "django.db.backends.mysql", "NAME": "db", "USER": "root", "PASSWORD": "rootpw", "HOST": "127.0.0.1", "OPTIONS": {"charset": "utf8mb4"}}}'
    steps:
      - checkout
      - run:
          name: Update system
          command: |
            sudo apt-get update
            sudo apt-get install -y libgtk3.0-cil-dev libasound2 libasound2 libdbus-glib-1-2 libdbus-1-3 libgtk2.0-0 default-libmysqlclient-dev
      - run:
          name: Install geckodriver
          command: |
            wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
            tar xzf geckodriver-v0.26.0-linux64.tar.gz
            sudo mv geckodriver /usr/local/bin/geckodriver
            which geckodriver
      - run:
          name: Install new firefox
          command: |
            wget https://archive.mozilla.org/pub/firefox/releases/70.0.1/linux-x86_64/en-US/firefox-70.0.1.tar.bz2
            tar jxf firefox-70.0.1.tar.bz2
            export PATH="$(pwd)/firefox/:$PATH"
      - run:
          name: Sync submodules
          command: git submodule sync
      - run:
          name: Update submodules
          command: git submodule update --init
      - run:
          name: Run tests
          command: |
            export PATH="$(pwd)/firefox/:$PATH"
            mkdir -p /tmp/coverage/$CIRCLE_SHA1
            virtualenv venv
            source venv/bin/activate
            pip -q install -r test_requirements.txt
            pip install -e .
            <<parameters.test_command>>
            if [ -e .coverage.* ]; then
                cp .coverage.* /tmp/coverage/$CIRCLE_SHA1/.
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
              - coverage

  coverage:
    docker:
      - image: <<parameters.docker_image>>
    parameters:
        docker_image:
            type: string
    steps:
      - checkout
      - run:
          name: Update system and install deps
          command: |
            sudo apt-get update
            virtualenv venv
            source venv/bin/activate
            pip install 'coverage==5.0.3'
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
              source venv/bin/activate
              coverage combine /tmp/workspace/coverage/$CIRCLE_SHA1/
              coverage report

  deploy:
    docker:
      - image: <<parameters.docker_image>>
    parameters:
        docker_image:
            type: string
        dist_type:
            type: string
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -U pip twine wheel
      - save_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: Verify commit is tagged and tag matches version
          command: |
            source venv/bin/activate
            python setup.py verify_tag
      - run:
          name: Initialize .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = opencraft" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create packages
          command: |
            source venv/bin/activate
            python setup.py <<parameters.dist_type>>
      - run:
          name: Upload to pypi
          command: |
            source venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          name: py35-quality
          test_command: make quality
          docker_image: circleci/python:3.5-buster-browsers
          filters:
            tags:
              only: /.*/
      - build:
          name: py35-unit
          test_command: make test.unit
          docker_image: circleci/python:3.5-buster-browsers
          filters:
            tags:
              only: /.*/
      - build:
          name: py35-integration
          test_command: make test.integration
          docker_image: circleci/python:3.5-buster-browsers
          filters:
            tags:
              only: /.*/
      - coverage:
          name: py35-coverage
          docker_image: circleci/python:3.5-buster
          filters:
            tags:
              only: /.*/
          requires:
              - py35-quality
              - py35-unit
              - py35-integration
      - deploy:
          name: py35-deploy-bdist_wheel
          docker_image: circleci/python:3.5-buster
          dist_type: bdist_wheel
          requires:
            - py35-coverage
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
